import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export const meta = () => {
    return [
        { title: "New Campaign - SmartStack" },
        { name: "description", content: "Create a new upsell campaign" },
    ];
};
export default function NewCampaign() {
    return (_jsxs("div", { className: "min-h-screen bg-gray-50", children: [_jsx("nav", { className: "bg-white shadow", children: _jsx("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4", children: _jsx("h1", { className: "text-2xl font-bold text-gray-900", children: "New Campaign" }) }) }), _jsx("main", { className: "max-w-2xl mx-auto px-4 sm:px-6 lg:px-8 py-12", children: _jsx("div", { className: "bg-white rounded-lg shadow p-8", children: _jsxs("form", { className: "space-y-6", children: [_jsxs("div", { children: [_jsx("label", { htmlFor: "name", className: "block text-sm font-medium text-gray-900", children: "Campaign Name" }), _jsx("input", { type: "text", id: "name", className: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500", placeholder: "e.g., Summer Bundle Offer" })] }), _jsxs("div", { children: [_jsx("label", { htmlFor: "trigger", className: "block text-sm font-medium text-gray-900", children: "Trigger Type" }), _jsxs("select", { id: "trigger", className: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500", children: [_jsx("option", { children: "Post-Purchase (Thank You Page)" }), _jsx("option", { children: "Cart Page" })] })] }), _jsxs("div", { children: [_jsx("label", { htmlFor: "method", className: "block text-sm font-medium text-gray-900", children: "Product Selection Method" }), _jsxs("select", { id: "method", className: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500", children: [_jsx("option", { children: "Manual Selection" }), _jsx("option", { children: "Tag-Based Rules" })] })] }), _jsxs("div", { className: "flex gap-4", children: [_jsx("button", { type: "submit", className: "inline-block bg-indigo-600 hover:bg-indigo-700 text-white font-semibold py-2 px-8 rounded-lg transition", children: "Continue" }), _jsx("a", { href: "/campaigns", className: "inline-block bg-gray-200 hover:bg-gray-300 text-gray-900 font-semibold py-2 px-8 rounded-lg transition", children: "Cancel" })] })] }) }) })] }));
}
