import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export const meta = () => {
    return [
        { title: "Settings - SmartStack" },
        { name: "description", content: "Manage your app settings" },
    ];
};
export default function Settings() {
    return (_jsxs("div", { className: "min-h-screen bg-gray-50", children: [_jsx("nav", { className: "bg-white shadow", children: _jsx("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4", children: _jsx("h1", { className: "text-2xl font-bold text-gray-900", children: "Settings" }) }) }), _jsx("main", { className: "max-w-2xl mx-auto px-4 sm:px-6 lg:px-8 py-12", children: _jsx("div", { className: "bg-white rounded-lg shadow p-8", children: _jsxs("form", { className: "space-y-6", children: [_jsxs("div", { children: [_jsx("label", { htmlFor: "timezone", className: "block text-sm font-medium text-gray-900", children: "Timezone" }), _jsxs("select", { id: "timezone", className: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500", children: [_jsx("option", { children: "UTC" }), _jsx("option", { children: "EST" }), _jsx("option", { children: "CST" }), _jsx("option", { children: "MST" }), _jsx("option", { children: "PST" })] })] }), _jsxs("div", { children: [_jsx("label", { htmlFor: "currency", className: "block text-sm font-medium text-gray-900", children: "Currency" }), _jsxs("select", { id: "currency", className: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500", children: [_jsx("option", { children: "USD" }), _jsx("option", { children: "EUR" }), _jsx("option", { children: "GBP" }), _jsx("option", { children: "CAD" }), _jsx("option", { children: "AUD" })] })] }), _jsxs("div", { children: [_jsx("label", { htmlFor: "email", className: "block text-sm font-medium text-gray-900", children: "Email for Notifications" }), _jsx("input", { type: "email", id: "email", className: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500", placeholder: "your@email.com" })] }), _jsx("button", { type: "submit", className: "inline-block bg-indigo-600 hover:bg-indigo-700 text-white font-semibold py-2 px-8 rounded-lg transition", children: "Save Settings" })] }) }) })] }));
}
